apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: training-operator
  name: training-operator
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - mpijobs
      - tfjobs
      - mxjobs
      - pytorchjobs
      - xgboostjobs
      - mpijobs/status
      - tfjobs/status
      - pytorchjobs/status
      - mxjobs/status
      - xgboostjobs/status
      - mpijobs/finalizers
      - tfjobs/finalizers
      - mxjobs/finalizers
      - pytorchjobs/finalizers
      - xgboostjobs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - pods/finalizers
      - services/finalizers
      - endpoints/finalizers
      - events/finalizers
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
    - configmaps
    - secrets
    - serviceaccounts
    verbs:
      - create
      - list
      - watch
      - update
  - apiGroups:
      - scheduling.volcano.sh
    resources:
      - podgroups
      - podgroups/finalizers
    verbs:
      - "*"
